package org.coologic.cacaocat.research001.case001.domain.type;

import lombok.Getter;

//操作码类型
@Getter
public enum OpcodeTypeEnum {
    NOP(0, "nop", null, InstructionTypeEnum.NO_TYPE, "空操作"),
    ACONST_NULL(1, "aconst_null", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ICONST_M1(2, "iconst_m1", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ICONST_0(3, "iconst_0", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ICONST_1(4, "iconst_1", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ICONST_2(5, "iconst_2", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ICONST_3(6, "iconst_3", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ICONST_4(7, "iconst_4", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ICONST_5(8, "iconst_5", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    LCONST_0(9, "lconst_0", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    LCONST_1(10, "lconst_1", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    FCONST_0(11, "fconst_0", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    FCONST_1(12, "fconst_1", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    FCONST_2(13, "fconst_2", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    DCONST_0(14, "dconst_0", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    DCONST_1(15, "dconst_1", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    BIPUSH(16, "bipush", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    SIPUSH(17, "sipush", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    LDC(18, "ldc", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    LDC_W(19, "ldc_w", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    LDC2_W(20, "ldc2_w", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ILOAD(21, "iload", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    LLOAD(22, "lload", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    FLOAD(23, "fload", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    DLOAD(24, "dload", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ALOAD(25, "aload", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ILOAD_0(26, "iload_0", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ILOAD_1(27, "iload_1", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ILOAD_2(28, "iload_2", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ILOAD_3(29, "iload_3", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    LLOAD_0(30, "lload_0", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    LLOAD_1(31, "lload_1", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    LLOAD_2(32, "lload_2", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    LLOAD_3(33, "lload_3", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    FLOAD_0(34, "fload_0", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    FLOAD_1(35, "fload_1", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    FLOAD_2(36, "fload_2", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    FLOAD_3(37, "fload_3", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    DLOAD_0(38, "dload_0", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    DLOAD_1(39, "dload_1", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    DLOAD_2(40, "dload_2", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    DLOAD_3(41, "dload_3", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ALOAD_0(42, "aload_0", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ALOAD_1(43, "aload_1", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ALOAD_2(44, "aload_2", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ALOAD_3(45, "aload_3", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    IALOAD(46, "iaload", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    LALOAD(47, "laload", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    FALOAD(48, "faload", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    DALOAD(49, "daload", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    AALOAD(50, "aaload", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    BALOAD(51, "baload", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    CALOAD(52, "caload", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    SALOAD(53, "saload", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    ISTORE(54, "istore", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    LSTORE(55, "lstore", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    FSTORE(56, "fstore", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    DSTORE(57, "dstore", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ASTORE(58, "astore", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ISTORE_0(59, "istore_0", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ISTORE_1(60, "istore_1", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ISTORE_2(61, "istore_2", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ISTORE_3(62, "istore_3", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    LSTORE_0(63, "lstore_0", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    LSTORE_1(64, "lstore_1", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    LSTORE_2(65, "lstore_2", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    LSTORE_3(66, "lstore_3", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    FSTORE_0(67, "fstore_0", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    FSTORE_1(68, "fstore_1", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    FSTORE_2(69, "fstore_2", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    FSTORE_3(70, "fstore_3", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    DSTORE_0(71, "dstore_0", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    DSTORE_1(72, "dstore_1", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    DSTORE_2(73, "dstore_2", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    DSTORE_3(74, "dstore_3", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ASTORE_0(75, "astore_0", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ASTORE_1(76, "astore_1", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ASTORE_2(77, "astore_2", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    ASTORE_3(78, "astore_3", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    IASTORE(79, "iastore", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    LASTORE(80, "lastore", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    FASTORE(81, "fastore", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    DASTORE(82, "dastore", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    AASTORE(83, "aastore", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    BASTORE(84, "bastore", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    CASTORE(85, "castore", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    SASTORE(86, "sastore", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    POP(87, "pop", null, InstructionTypeEnum.OPERAND_STACK_MANAGEMENT, ""),
    POP2(88, "pop2", null, InstructionTypeEnum.OPERAND_STACK_MANAGEMENT, ""),
    DUP(89, "dup", null, InstructionTypeEnum.OPERAND_STACK_MANAGEMENT, ""),
    DUP_X1(90, "dup_x1", null, InstructionTypeEnum.OPERAND_STACK_MANAGEMENT, ""),
    DUP_X2(91, "dup_x2", null, InstructionTypeEnum.OPERAND_STACK_MANAGEMENT, ""),
    DUP2(92, "dup2", null, InstructionTypeEnum.OPERAND_STACK_MANAGEMENT, ""),
    DUP2_X1(93, "dup2_x1", null, InstructionTypeEnum.OPERAND_STACK_MANAGEMENT, ""),
    DUP2_X2(94, "dup2_x2", null, InstructionTypeEnum.OPERAND_STACK_MANAGEMENT, ""),
    SWAP(95, "swap", null, InstructionTypeEnum.OPERAND_STACK_MANAGEMENT, ""),
    IADD(96, "iadd", null, InstructionTypeEnum.ARITHMETIC, ""),
    LADD(97, "ladd", null, InstructionTypeEnum.ARITHMETIC, ""),
    FADD(98, "fadd", null, InstructionTypeEnum.ARITHMETIC, ""),
    DADD(99, "dadd", null, InstructionTypeEnum.ARITHMETIC, ""),
    ISUB(100, "isub", null, InstructionTypeEnum.ARITHMETIC, ""),
    LSUB(101, "lsub", null, InstructionTypeEnum.ARITHMETIC, ""),
    FSUB(102, "fsub", null, InstructionTypeEnum.ARITHMETIC, ""),
    DSUB(103, "dsub", null, InstructionTypeEnum.ARITHMETIC, ""),
    IMUL(104, "imul", null, InstructionTypeEnum.ARITHMETIC, ""),
    LMUL(105, "lmul", null, InstructionTypeEnum.ARITHMETIC, ""),
    FMUL(106, "fmul", null, InstructionTypeEnum.ARITHMETIC, ""),
    DMUL(107, "dmul", null, InstructionTypeEnum.ARITHMETIC, ""),
    IDIV(108, "idiv", null, InstructionTypeEnum.ARITHMETIC, ""),
    LDIV(109, "ldiv", null, InstructionTypeEnum.ARITHMETIC, ""),
    FDIV(110, "fdiv", null, InstructionTypeEnum.ARITHMETIC, ""),
    DDIV(111, "ddiv", null, InstructionTypeEnum.ARITHMETIC, ""),
    IREM(112, "irem", null, InstructionTypeEnum.ARITHMETIC, ""),
    LREM(113, "lrem", null, InstructionTypeEnum.ARITHMETIC, ""),
    FREM(114, "frem", null, InstructionTypeEnum.ARITHMETIC, ""),
    DREM(115, "drem", null, InstructionTypeEnum.ARITHMETIC, ""),
    INEG(116, "ineg", null, InstructionTypeEnum.ARITHMETIC, ""),
    LNEG(117, "lneg", null, InstructionTypeEnum.ARITHMETIC, ""),
    FNEG(118, "fneg", null, InstructionTypeEnum.ARITHMETIC, ""),
    DNEG(119, "dneg", null, InstructionTypeEnum.ARITHMETIC, ""),
    ISHL(120, "ishl", null, InstructionTypeEnum.ARITHMETIC, ""),
    LSHL(121, "lshl", null, InstructionTypeEnum.ARITHMETIC, ""),
    ISHR(122, "ishr", null, InstructionTypeEnum.ARITHMETIC, ""),
    LSHR(123, "lshr", null, InstructionTypeEnum.ARITHMETIC, ""),
    IUSHR(124, "iushr", null, InstructionTypeEnum.ARITHMETIC, ""),
    LUSHR(125, "lushr", null, InstructionTypeEnum.ARITHMETIC, ""),
    IAND(126, "iand", null, InstructionTypeEnum.ARITHMETIC, ""),
    LAND(127, "land", null, InstructionTypeEnum.ARITHMETIC, ""),
    IOR(128, "ior", null, InstructionTypeEnum.ARITHMETIC, ""),
    LOR(129, "lor", null, InstructionTypeEnum.ARITHMETIC, ""),
    IXOR(130, "ixor", null, InstructionTypeEnum.ARITHMETIC, ""),
    LXOR(131, "lxor", null, InstructionTypeEnum.ARITHMETIC, ""),
    IINC(132, "iinc", null, InstructionTypeEnum.ARITHMETIC, ""),
    I2L(133, "i2l", null, InstructionTypeEnum.TYPE_CONVERSION, ""),
    I2F(134, "i2f", null, InstructionTypeEnum.TYPE_CONVERSION, ""),
    I2D(135, "i2d", null, InstructionTypeEnum.TYPE_CONVERSION, ""),
    L2I(136, "l2i", null, InstructionTypeEnum.TYPE_CONVERSION, ""),
    L2F(137, "l2f", null, InstructionTypeEnum.TYPE_CONVERSION, ""),
    L2D(138, "l2d", null, InstructionTypeEnum.TYPE_CONVERSION, ""),
    F2I(139, "f2i", null, InstructionTypeEnum.TYPE_CONVERSION, ""),
    F2L(140, "f2l", null, InstructionTypeEnum.TYPE_CONVERSION, ""),
    F2D(141, "f2d", null, InstructionTypeEnum.TYPE_CONVERSION, ""),
    D2I(142, "d2i", null, InstructionTypeEnum.TYPE_CONVERSION, ""),
    D2L(143, "d2l", null, InstructionTypeEnum.TYPE_CONVERSION, ""),
    D2F(144, "d2f", null, InstructionTypeEnum.TYPE_CONVERSION, ""),
    I2B(145, "i2b", null, InstructionTypeEnum.TYPE_CONVERSION, ""),
    I2C(146, "i2c", null, InstructionTypeEnum.TYPE_CONVERSION, ""),
    I2S(147, "i2s", null, InstructionTypeEnum.TYPE_CONVERSION, ""),
    LCMP(148, "lcmp", null, InstructionTypeEnum.ARITHMETIC, "比较指令"),
    FCMPL(149, "fcmpl", null, InstructionTypeEnum.ARITHMETIC, "比较指令"),
    FCMPG(150, "fcmpg", null, InstructionTypeEnum.ARITHMETIC, "比较指令"),
    DCMPL(151, "dcmpl", null, InstructionTypeEnum.ARITHMETIC, "比较指令"),
    DCMPG(152, "dcmpg", null, InstructionTypeEnum.ARITHMETIC, "比较指令"),
    IFEQ(153, "ifeq", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    IFNE(154, "ifne", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    IFLT(155, "iflt", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    IFGE(156, "ifge", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    IFGT(157, "ifgt", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    IFLE(158, "ifle", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    IF_ICMPEQ(159, "if_icmpeq", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    IF_ICMPNE(160, "if_icmpne", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    IF_ICMPLT(161, "if_icmplt", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    IF_ICMPGE(162, "if_icmpge", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    IF_ICMPGT(163, "if_icmpgt", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    IF_ICMPLE(164, "if_icmple", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    IF_ACMPEQ(165, "if_acmpeq", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    IF_ACMPNE(166, "if_acmpne", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    GOTO(167, "goto", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    JSR(168, "jsr", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    RET(169, "ret", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    TABLESWITCH(170, "tableswitch", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    LOOKUPSWITCH(171, "lookupswitch", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    IRETURN(172, "ireturn", null, InstructionTypeEnum.METHOD_INVOCATION_AND_RETURN, ""),
    LRETURN(173, "lreturn", null, InstructionTypeEnum.METHOD_INVOCATION_AND_RETURN, ""),
    FRETURN(174, "freturn", null, InstructionTypeEnum.METHOD_INVOCATION_AND_RETURN, ""),
    DRETURN(175, "dreturn", null, InstructionTypeEnum.METHOD_INVOCATION_AND_RETURN, ""),
    ARETURN(176, "areturn", null, InstructionTypeEnum.METHOD_INVOCATION_AND_RETURN, ""),
    RETURN(177, "return", null, InstructionTypeEnum.METHOD_INVOCATION_AND_RETURN, ""),
    GETSTATIC(178, "getstatic", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    PUTSTATIC(179, "putstatic", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    GETFIELD(180, "getfield", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    PUTFIELD(181, "putfield", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    INVOKEVIRTUAL(182, "invokevirtual", null, InstructionTypeEnum.METHOD_INVOCATION_AND_RETURN, ""),
    INVOKESPECIAL(183, "invokespecial", null, InstructionTypeEnum.METHOD_INVOCATION_AND_RETURN, ""),
    INVOKESTATIC(184, "invokestatic", null, InstructionTypeEnum.METHOD_INVOCATION_AND_RETURN, ""),
    INVOKEINTERFACE(185, "invokeinterface", null, InstructionTypeEnum.METHOD_INVOCATION_AND_RETURN, ""),
    INVOKEDYNAMIC(186, "invokedynamic", null, InstructionTypeEnum.METHOD_INVOCATION_AND_RETURN, ""),
    NEW(187, "new", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    NEWARRAY(188, "newarray", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    ANEWARRAY(189, "anewarray", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    ARRAYLENGTH(190, "arraylength", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    ATHROW(191, "athrow", null, InstructionTypeEnum.THROWING, ""),
    CHECKCAST(192, "checkcast", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    INSTANCEOF(193, "instanceof", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    MONITORENTER(194, "monitorenter", null, InstructionTypeEnum.SYNCHRONIZATION, ""),
    MONITOREXIT(195, "monitorexit", null, InstructionTypeEnum.SYNCHRONIZATION, ""),
    WIDE(196, "wide", null, InstructionTypeEnum.LOAD_AND_STORE, ""),
    MULTIANEWARRAY(197, "multianewarray", null, InstructionTypeEnum.OBJECT_CREATION_AND_MANIPULATION, ""),
    IFNULL(198, "ifnull", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    IFNONNULL(199, "ifnonnull", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    GOTO_W(200, "goto_w", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    JSR_W(201, "jsr_w", null, InstructionTypeEnum.CONTROL_TRANSFER, ""),
    BREAKPOINT(202, "breakpoint", null, InstructionTypeEnum.NO_TYPE, "调试断点操作码"),
    IMPDEP1(254, "impdep1", null, InstructionTypeEnum.NO_TYPE, "保留操作码"),
    IMPDEP2(255, "impdep2", null, InstructionTypeEnum.NO_TYPE, "保留操作码");

    private final int    tag;
    private final String          code;
    //操作数类型
    private final OperandTypeEnum operandType;
    private final InstructionTypeEnum instructionType;
    private final String desc;

    OpcodeTypeEnum(int tag, String code, OperandTypeEnum operandType,
                   InstructionTypeEnum instructionType, String desc) {
        this.tag = tag;
        this.code = code;
        this.operandType = operandType;
        this.instructionType = instructionType;
        this.desc = desc;
    }

    public static OpcodeTypeEnum getByTag(int tag) {
        for (var value : OpcodeTypeEnum.values()) {
            if (value.tag == tag) {
                return value;
            }
        }
        return null;
    }
}