package org.coologic.cacaocat.research001.case001.domain.type;

import lombok.Getter;

//操作码类型
@Getter
public enum OpcodeTypeEnum {
    NOP(0, "nop", null, null),
    ACONST_NULL(1, "aconst_null", null, null),
    ICONST_M1(2, "iconst_m1", null, null),
    ICONST_0(3, "iconst_0", null, null),
    ICONST_1(4, "iconst_1", null, null),
    ICONST_2(5, "iconst_2", null, null),
    ICONST_3(6, "iconst_3", null, null),
    ICONST_4(7, "iconst_4", null, null),
    ICONST_5(8, "iconst_5", null, null),
    LCONST_0(9, "lconst_0", null, null),
    LCONST_1(10, "lconst_1", null, null),
    FCONST_0(11, "fconst_0", null, null),
    FCONST_1(12, "fconst_1", null, null),
    FCONST_2(13, "fconst_2", null, null),
    DCONST_0(14, "dconst_0", null, null),
    DCONST_1(15, "dconst_1", null, null),
    BIPUSH(16, "bipush", null, null),
    SIPUSH(17, "sipush", null, null),
    LDC(18, "ldc", null, null),
    LDC_W(19, "ldc_w", null, null),
    LDC2_W(20, "ldc2_w", null, null),
    ILOAD(21, "iload", null, null),
    LLOAD(22, "lload", null, null),
    FLOAD(23, "fload", null, null),
    DLOAD(24, "dload", null, null),
    ALOAD(25, "aload", null, null),
    ILOAD_0(26, "iload_0", null, null),
    ILOAD_1(27, "iload_1", null, null),
    ILOAD_2(28, "iload_2", null, null),
    ILOAD_3(29, "iload_3", null, null),
    LLOAD_0(30, "lload_0", null, null),
    LLOAD_1(31, "lload_1", null, null),
    LLOAD_2(32, "lload_2", null, null),
    LLOAD_3(33, "lload_3", null, null),
    FLOAD_0(34, "fload_0", null, null),
    FLOAD_1(35, "fload_1", null, null),
    FLOAD_2(36, "fload_2", null, null),
    FLOAD_3(37, "fload_3", null, null),
    DLOAD_0(38, "dload_0", null, null),
    DLOAD_1(39, "dload_1", null, null),
    DLOAD_2(40, "dload_2", null, null),
    DLOAD_3(41, "dload_3", null, null),
    ALOAD_0(42, "aload_0", null, null),
    ALOAD_1(43, "aload_1", null, null),
    ALOAD_2(44, "aload_2", null, null),
    ALOAD_3(45, "aload_3", null, null),
    IALOAD(46, "iaload", null, null),
    LALOAD(47, "laload", null, null),
    FALOAD(48, "faload", null, null),
    DALOAD(49, "daload", null, null),
    AALOAD(50, "aaload", null, null),
    BALOAD(51, "baload", null, null),
    CALOAD(52, "caload", null, null),
    SALOAD(53, "saload", null, null),
    ISTORE(54, "istore", null, null),
    LSTORE(55, "lstore", null, null),
    FSTORE(56, "fstore", null, null),
    DSTORE(57, "dstore", null, null),
    ASTORE(58, "astore", null, null),
    ISTORE_0(59, "istore_0", null, null),
    ISTORE_1(60, "istore_1", null, null),
    ISTORE_2(61, "istore_2", null, null),
    ISTORE_3(62, "istore_3", null, null),
    LSTORE_0(63, "lstore_0", null, null),
    LSTORE_1(64, "lstore_1", null, null),
    LSTORE_2(65, "lstore_2", null, null),
    LSTORE_3(66, "lstore_3", null, null),
    FSTORE_0(67, "fstore_0", null, null),
    FSTORE_1(68, "fstore_1", null, null),
    FSTORE_2(69, "fstore_2", null, null),
    FSTORE_3(70, "fstore_3", null, null),
    DSTORE_0(71, "dstore_0", null, null),
    DSTORE_1(72, "dstore_1", null, null),
    DSTORE_2(73, "dstore_2", null, null),
    DSTORE_3(74, "dstore_3", null, null),
    ASTORE_0(75, "astore_0", null, null),
    ASTORE_1(76, "astore_1", null, null),
    ASTORE_2(77, "astore_2", null, null),
    ASTORE_3(78, "astore_3", null, null),
    IASTORE(79, "iastore", null, null),
    LASTORE(80, "lastore", null, null),
    FASTORE(81, "fastore", null, null),
    DASTORE(82, "dastore", null, null),
    AASTORE(83, "aastore", null, null),
    BASTORE(84, "bastore", null, null),
    CASTORE(85, "castore", null, null),
    SASTORE(86, "sastore", null, null),
    POP(87, "pop", null, null),
    POP2(88, "pop2", null, null),
    DUP(89, "dup", null, null),
    DUP_X1(90, "dup_x1", null, null),
    DUP_X2(91, "dup_x2", null, null),
    DUP2(92, "dup2", null, null),
    DUP2_X1(93, "dup2_x1", null, null),
    DUP2_X2(94, "dup2_x2", null, null),
    SWAP(95, "swap", null, null),
    IADD(96, "iadd", null, null),
    LADD(97, "ladd", null, null),
    FADD(98, "fadd", null, null),
    DADD(99, "dadd", null, null),
    ISUB(100, "isub", null, null),
    LSUB(101, "lsub", null, null),
    FSUB(102, "fsub", null, null),
    DSUB(103, "dsub", null, null),
    IMUL(104, "imul", null, null),
    LMUL(105, "lmul", null, null),
    FMUL(106, "fmul", null, null),
    DMUL(107, "dmul", null, null),
    IDIV(108, "idiv", null, null),
    LDIV(109, "ldiv", null, null),
    FDIV(110, "fdiv", null, null),
    DDIV(111, "ddiv", null, null),
    IREM(112, "irem", null, null),
    LREM(113, "lrem", null, null),
    FREM(114, "frem", null, null),
    DREM(115, "drem", null, null),
    INEG(116, "ineg", null, null),
    LNEG(117, "lneg", null, null),
    FNEG(118, "fneg", null, null),
    DNEG(119, "dneg", null, null),
    ISHL(120, "ishl", null, null),
    LSHL(121, "lshl", null, null),
    ISHR(122, "ishr", null, null),
    LSHR(123, "lshr", null, null),
    IUSHR(124, "iushr", null, null),
    LUSHR(125, "lushr", null, null),
    IAND(126, "iand", null, null),
    LAND(127, "land", null, null),
    IOR(128, "ior", null, null),
    LOR(129, "lor", null, null),
    IXOR(130, "ixor", null, null),
    LXOR(131, "lxor", null, null),
    IINC(132, "iinc", null, null),
    I2L(133, "i2l", null, null),
    I2F(134, "i2f", null, null),
    I2D(135, "i2d", null, null),
    L2I(136, "l2i", null, null),
    L2F(137, "l2f", null, null),
    L2D(138, "l2d", null, null),
    F2I(139, "f2i", null, null),
    F2L(140, "f2l", null, null),
    F2D(141, "f2d", null, null),
    D2I(142, "d2i", null, null),
    D2L(143, "d2l", null, null),
    D2F(144, "d2f", null, null),
    I2B(145, "i2b", null, null),
    I2C(146, "i2c", null, null),
    I2S(147, "i2s", null, null),
    LCMP(148, "lcmp", null, null),
    FCMPL(149, "fcmpl", null, null),
    FCMPG(150, "fcmpg", null, null),
    DCMPL(151, "dcmpl", null, null),
    DCMPG(152, "dcmpg", null, null),
    IFEQ(153, "ifeq", null, null),
    IFNE(154, "ifne", null, null),
    IFLT(155, "iflt", null, null),
    IFGE(156, "ifge", null, null),
    IFGT(157, "ifgt", null, null),
    IFLE(158, "ifle", null, null),
    IF_ICMPEQ(159, "if_icmpeq", null, null),
    IF_ICMPNE(160, "if_icmpne", null, null),
    IF_ICMPLT(161, "if_icmplt", null, null),
    IF_ICMPGE(162, "if_icmpge", null, null),
    IF_ICMPGT(163, "if_icmpgt", null, null),
    IF_ICMPLE(164, "if_icmple", null, null),
    IF_ACMPEQ(165, "if_acmpeq", null, null),
    IF_ACMPNE(166, "if_acmpne", null, null),
    GOTO(167, "goto", null, null),
    JSR(168, "jsr", null, null),
    RET(169, "ret", null, null),
    TABLESWITCH(170, "tableswitch", null, null),
    LOOKUPSWITCH(171, "lookupswitch", null, null),
    IRETURN(172, "ireturn", null, null),
    LRETURN(173, "lreturn", null, null),
    FRETURN(174, "freturn", null, null),
    DRETURN(175, "dreturn", null, null),
    ARETURN(176, "areturn", null, null),
    RETURN(177, "return", null, null),
    GETSTATIC(178, "getstatic", null, null),
    PUTSTATIC(179, "putstatic", null, null),
    GETFIELD(180, "getfield", null, null),
    PUTFIELD(181, "putfield", null, null),
    INVOKEVIRTUAL(182, "invokevirtual", null, null),
    INVOKESPECIAL(183, "invokespecial", null, null),
    INVOKESTATIC(184, "invokestatic", null, null),
    INVOKEINTERFACE(185, "invokeinterface", null, null),
    INVOKEDYNAMIC(186, "invokedynamic", null, null),
    NEW(187, "new", null, null),
    NEWARRAY(188, "newarray", null, null),
    ANEWARRAY(189, "anewarray", null, null),
    ARRAYLENGTH(190, "arraylength", null, null),
    ATHROW(191, "athrow", null, null),
    CHECKCAST(192, "checkcast", null, null),
    INSTANCEOF(193, "instanceof", null, null),
    MONITORENTER(194, "monitorenter", null, null),
    MONITOREXIT(195, "monitorexit", null, null),
    WIDE(196, "wide", null, null),
    MULTIANEWARRAY(197, "multianewarray", null, null),
    IFNULL(198, "ifnull", null, null),
    IFNONNULL(199, "ifnonnull", null, null),
    GOTO_W(200, "goto_w", null, null),
    JSR_W(201, "jsr_w", null, null),
    BREAKPOINT(202, "breakpoint", null, null),
    IMPDEP1(254, "impdep1", null, null),
    IMPDEP2(255, "impdep2", null, null);

    private final int    tag;
    private final String          code;
    //操作数类型
    private final OperandTypeEnum operandType;
    private final InstructionTypeEnum instructionType;

    OpcodeTypeEnum(int tag, String code, OperandTypeEnum operandType,
                   InstructionTypeEnum instructionType) {
        this.tag = tag;
        this.code = code;
        this.operandType = operandType;
        this.instructionType = instructionType;
    }

    public static OpcodeTypeEnum getByTag(int tag) {
        for (var value : OpcodeTypeEnum.values()) {
            if (value.tag == tag) {
                return value;
            }
        }
        return null;
    }
}